[build]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-python"

[functions]
  python_version = "3.9"

[[functions]]
  path = "netlify/functions/python-viz"
  runtime = "python3.9"
