[build]
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/*.py"]
  external_node_modules = ["undici"]
